version: '3.3'
services:
    uit-agent:
        environment:
          ADMIN_PORT: 5000
          AGENT_PORT: 8000
          WEBHOOK_URL: http://uit-service:3000/webhooks
        build:
            context: .
            dockerfile: ./Dockerfile.agent
        ports:
            - "5000:5000"
            - "8000:8000"
        networks:
            - identifyme_net
        volumes:
            - aca-py:/home/indy/.indy_client/wallet
        command: start -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 5000 -e localhost --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --label "University of Information Technology" --auto-accept-invites --auto-accept-requests --admin-insecure-mode --log-level info
    uit-service:
        restart: always
        image: uit-service
        build: 
            context: .
            dockerfile: ./Dockerfile.service
        depends_on:
            - uit-agent
        networks:
            - identifyme_net
        environment:
            PORT: 3000
            AGENT_URL: "http://uit-agent:5000"
        ports:
            - 3000:3000
volumes:
    aca-py:
networks:
    identifyme_net: